export * from './Learn';
export * from './OldLogin';
export * from './Login';
export * from './Signup';
export * from './Welcome';
export * from './Home';
export * from './About';
export * from './Contact';
export * from './Error';
